-define(DNS_SERVERS, [{8,8,8,8},{8,8,4,4},{1,1,1,1},{9,9,9,9}]).
-define(DNS_TIMEOUT, 5).
-define(DNS_FILE, "/home/sendai/snitch_domains.txt").
-define(SERVER, ?MODULE).
-define(TABLE_NAME, mytable).
-define(DEFAULT_TICK, 60).
-define(DEFAULT_CHECKPOINT, 5 * 60 * 1000).
-define(INIT_TICK, 5).
-define(INIT_CHECKPOINT, 10 * 1000).
