name: Build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      OTP_VERSION: 25.1.2
      REBAR_VERSION: 3.20.0
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR_VERSION }"
      - uses: actions/cache@v2
        with:
          key: "${{ env.OTP_VERSION }}-${{ env.REBAR_VERSION }}"
          path: ~/.cache/rebar3
      - run: rebar3 ct
      - run: rebar3 dialyzer

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/azimut/snitch:latest
